apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: us-central1-docker.pkg.dev/nitin-project-gcp/sims/student-api:latest
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 5050
        readinessProbe:
          httpGet:
            path: /api/v1/students
            port: web
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"